-- Ранжирование
WITH all_contracts AS (
select * 
, MAX(OSZ) OVER(PARTITION BY TB) as MAX_OSZ 
, AVG(PROCENT_RATE) OVER(PARTITION BY TB, SEGMENT) as AVG_PROCENT_RATE
, COUNT(*) OVER() TOTAL_DOG
, ROW_NUMBER() OVER()
, RANK() OVER(ORDER BY OSZ DESC)
, DENSE_RANK() OVER(ORDER BY OSZ DESC)
, RANK() OVER(PARTITION BY TB ORDER BY OSZ DESC) rn
from T
)
SELECT * FROM all_contracts
WHERE rn = 1
ORDER BY 1, 14